name: CI/CD Pipeline

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Deploy to Database
        run: |
            mysql -h "${{ secrets.DB_HOST }}" -u "${{ secrets.DB_USER }}" --password="${{ secrets.DB_PASSWORD }}" "${{ secrets.DB_NAME }}" < schema_changes_git.sql
